local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

  # Need to setup S3 storage later for prod
  # Store under storage/production.yml